training:
    batch_size: 32
    epochs: 1000
    learning_rate: 0.0001


input_features:
    -
        name: samples
        type: sequence
        encoder: rnn
        
    -
        name: sensor
        type: category

output_features:
    -
        name: gait
        type: category